name: users-api

on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
        pip install coverage

    - name: Lint with pylint
      run: |
        pylint users tests

    - name: Test with coverage
      run: |
        coverage run -m unittest discover tests -t . -p "*.py"
        coverage report -m
